// simple-cms/sveltekit/src/lib/components/blocks/ButtonGroup.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import Button, { type ButtonProps } from './Button.svelte';

	interface ButtonGroupProps {
		buttons: Array<ButtonProps>;
		[key: string]: any;
	}

	let { buttons, ...props }: ButtonGroupProps = $props();

	const containerClasses = $derived(cn('flex gap-4', props.class));
</script>

{#if buttons && buttons.length > 0}
	<div class={containerClasses}>
		{#each buttons as button, index}
			<Button {...button}>{button.label}</Button>
		{/each}
	</div>
{/if}

// simple-cms/astro/src/components/blocks/ButtonGroup.tsx
import React from "react";
import Button, { type ButtonProps } from "./Button";
import { cn } from "@/lib/utils";

export interface ButtonGroupProps {
  buttons: Array<ButtonProps>;
  className?: string;
}

const ButtonGroup = ({ buttons, className }: ButtonGroupProps) => {
  if (!buttons || !buttons.length) return null;

  const containerClasses = cn("flex gap-4", className);

  return (
    <div className={containerClasses}>
      {buttons.map((button, index) => (
        <Button key={index} {...button} />
      ))}
    </div>
  );
};

export default ButtonGroup;
