// simple-cms/nuxt/app/components/Footer.vue
<script setup lang="ts">
import { computed } from 'vue';

export interface SocialLink {
	service: string;
	url: string;
}

export interface NavigationItem {
	id: string;
	title: string;
	url?: string | null;
	page?: {
		permalink?: string | null;
	};
}

export interface FooterProps {
	navigation: {
		items: NavigationItem[];
	};
	globals: {
		logo?: string | null;
		logo_dark_mode?: string | null;
		description?: string | null;
		social_links?: SocialLink[];
	};
}

const props = defineProps<FooterProps>();
const runtimeConfig = useRuntimeConfig();

const lightLogoUrl = computed(() =>
	props.globals.logo ? `${runtimeConfig.public.directusUrl}/assets/${props.globals.logo}` : '/images/logo.svg',
);

const darkLogoUrl = computed(() =>
	props.globals.logo_dark_mode ? `${runtimeConfig.public.directusUrl}/assets/${props.globals.logo_dark_mode}` : '',
);
</script>

<template>
	<footer v-if="globals" class="bg-gray dark:bg-[var(--background-variant-color)] py-16">
		<Container class="text-foreground dark:text-white">
			<div class="flex flex-col md:flex-row justify-between items-start gap-8 pt-8">
				<div class="flex-1">
					<NuxtLink to="/" class="inline-block transition-opacity hover:opacity-70">
						<img
							v-if="lightLogoUrl"
							:src="lightLogoUrl"
							alt="Logo"
							:class="['w-[120px] h-auto', darkLogoUrl ? 'dark:hidden' : '']"
						/>
						<img
							v-if="darkLogoUrl"
							:src="darkLogoUrl"
							alt="Logo (Dark Mode)"
							class="w-[120px] h-auto hidden dark:block"
						/>
					</NuxtLink>

					<p v-if="props.globals.description" class="text-description mt-2">
						{{ props.globals.description }}
					</p>

					<!-- Social Links -->
					<div v-if="props.globals.social_links?.length" class="mt-4 flex space-x-4">
						<a
							v-for="social in props.globals.social_links"
							:key="social.service"
							:href="social.url"
							target="_blank"
							rel="noopener noreferrer"
							class="size-8 rounded bg-transparent inline-flex items-center justify-center transition-colors hover:opacity-70"
						>
							<img
								:src="`/icons/social/${social.service}.svg`"
								:alt="`${social.service} icon`"
								class="size-6 dark:invert"
							/>
						</a>
					</div>
				</div>

				<div class="flex flex-col items-start md:items-end flex-1">
					<nav v-if="props.navigation.items?.length" class="w-full md:w-auto text-left">
						<ul class="space-y-4">
							<li v-for="item in props.navigation.items" :key="item.id">
								<NuxtLink
									v-if="item.page?.permalink"
									:to="item.page.permalink"
									class="text-nav font-medium hover:underline"
								>
									{{ item.title }}
								</NuxtLink>
								<a v-else :href="item.url || '#'" class="text-nav font-medium hover:underline">
									{{ item.title }}
								</a>
							</li>
						</ul>
						<ThemeToggle class="dark:text-white mt-4" />
					</nav>
				</div>
			</div>
		</Container>
	</footer>
</template>

// cms/sveltekit/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import { PUBLIC_DIRECTUS_URL } from '$env/static/public';

	import { page } from '$app/state';
	import Container from '../ui/Container.svelte';
	import LightSwitch from './LightSwitch.svelte';

	const directusURL = PUBLIC_DIRECTUS_URL;

	const globals = $derived(page.data?.globals);
	const navPrimary = $derived(page.data?.footerNavigation);
	const lightLogoUrl = $derived(
		globals?.logo ? `${directusURL}/assets/${globals.logo}` : '/images/logo.svg'
	);
	const darkLogoUrl = $derived(
		globals?.logo_dark_mode ? `${directusURL}/assets/${globals.logo_dark_mode}` : ''
	);
</script>

<footer class="bg-gray py-16 dark:bg-[var(--background-variant-color)]">
	<Container class="text-foreground dark:text-white">
		<div class="flex flex-col items-start justify-between gap-8 pt-8 md:flex-row">
			<div class="flex-1">
				<a href="/">
					{#if lightLogoUrl}
						<img
							src={lightLogoUrl}
							alt="Logo"
							class={darkLogoUrl ? 'h-auto w-[120px] dark:hidden' : 'h-auto w-[120px]'}
						/>
					{/if}
					{#if darkLogoUrl}
						<img
							src={darkLogoUrl}
							alt="Logo (Dark Mode)"
							class="hidden h-auto w-[120px] dark:block"
						/>
					{/if}
				</a>
				{#if globals?.description}
					<p class="mt-2 text-description">{globals.description}</p>
				{/if}

				<!-- {/* Social Links */} -->
				{#if globals?.social_links}
					<div class="mt-4 flex space-x-4">
						{#each globals.social_links as social}
							<!-- key={social.service} -->
							<a
								href={social.url}
								target="_blank"
								rel="noopener noreferrer"
								class="hover:text-accent"
							>
								<img
									src={`/icons/social/${social.service === 'x' ? 'twitter' : social.service}.svg`}
									alt={`${social.service} icon`}
									width={24}
									height={24}
									class="size-6 dark:invert"
								/>
							</a>
						{/each}
					</div>
				{/if}
			</div>

			<div class="flex flex-1 flex-col items-start md:items-end">
				<nav class="w-full text-left md:w-auto">
					<ul class="space-y-4">
						{#if navPrimary?.items}
							{#each navPrimary.items as group (group.id)}
								<li>
									{#if group.children && group.page}
										<a href={group.page.permalink} class="text-nav font-medium hover:underline">
											{group.title}
										</a>
									{:else}
										<a href={group?.url || '#'} class="text-nav font-medium hover:underline">
											{group.title}
										</a>
									{/if}
								</li>
							{/each}
						{/if}
						<li>
							<LightSwitch />
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</Container>
</footer>
