// simple-cms/nuxt/app/components/forms/DynamicForm.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import { buildZodSchema } from '~/lib/zodSchemaBuilder';
import type { FormField } from '#shared/types/schema';
import BaseFormField from './BaseFormField.vue';
import BaseButton from '../base/BaseButton.vue';

const props = defineProps<{
	fields: FormField[];
	onSubmit: (data: Record<string, any>) => Promise<void> | void;
	submitLabel: string;
	formId?: string;
}>();

const isSubmitting = ref(false);

const { setAttr } = useVisualEditing();

const sortedFields = computed(() => [...props.fields].sort((a, b) => (a.sort || 0) - (b.sort || 0)));

const validFields = computed(() =>
	sortedFields.value.filter((field): field is FormField & { name: string } => field.name != null && field.name !== ''),
);

const schema = computed(() => {
	if (!validFields.value.length) return null;
	try {
		const zodSchema = buildZodSchema(validFields.value);
		return toTypedSchema(zodSchema);
	} catch {
		return null;
	}
});

const initialValues = computed(() => {
	if (!validFields.value.length) return {};
	return validFields.value.reduce(
		(defaults, field) => {
			const name = field.name;

			switch (field.type) {
				case 'checkbox':
					defaults[name] = false;
					break;
				case 'checkbox_group':
					defaults[name] = [];
					break;
				case 'select':
				case 'radio':
					defaults[name] = '';
					break;
				case 'file':
					defaults[name] = null;
					break;
				case 'textarea':
				case 'text':
				default:
					defaults[name] = '';
			}

			return defaults;
		},
		{} as Record<string, any>,
	);
});

const { handleSubmit, values } = useForm({
	validationSchema: schema,
	initialValues: initialValues.value,
});

const onSubmitForm = handleSubmit(async (formValues) => {
	if (isSubmitting.value) return;
	try {
		isSubmitting.value = true;
		await props.onSubmit(formValues);
	} finally {
		isSubmitting.value = false;
	}
});
</script>

<template>
	<form
		v-if="schema"
		:validation-schema="schema"
		:initial-values="initialValues"
		:data-directus="
			setAttr({
				collection: 'forms',
				item: props.formId,
				fields: 'fields',
				mode: 'popover',
			})
		"
		@submit.prevent="onSubmitForm"
	>
		<div class="flex flex-wrap gap-4">
			<div v-for="field in validFields" :key="field.id" class="w-full">
				<BaseFormField :field="field" :model-value="values[field.name]" />
			</div>

			<div class="w-full">
				<div>
					<BaseButton
						:id="`submit-${submitLabel.replace(/\s+/g, '-').toLowerCase()}`"
						type="submit"
						:label="submitLabel"
						:disabled="isSubmitting"
						icon="arrow"
						icon-position="right"
					/>
				</div>
			</div>
		</div>
	</form>
</template>

// simple-cms/astro/src/components/forms/DynamicForm.tsx
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { setAttr } from '@directus/visual-editing';
import Button from '@/components/blocks/Button';
import { Form } from '@/components/ui/form';
import Field from './FormField';
import { buildZodSchema } from '@/lib/zodSchemaBuilder';
import type { FormField as FormFieldType } from '@/types/directus-schema';

interface DynamicFormProps {
  fields: FormFieldType[];
  onSubmit: (data: Record<string, unknown>) => void;
  submitLabel: string;
  id: string;
}

const DynamicForm = ({ fields, onSubmit, submitLabel, id }: DynamicFormProps) => {
  const sortedFields = [...fields].sort((a, b) => (a.sort || 0) - (b.sort || 0));
  const formSchema = buildZodSchema(fields);
  type FormValues = z.infer<typeof formSchema>;

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: fields.reduce<Partial<FormValues>>((defaults, field) => {
      if (!field.name) return defaults;

      const name = field.name as keyof FormValues;

      switch (field.type) {
        case 'checkbox':
          defaults[name] = false as FormValues[typeof name];
          break;
        case 'checkbox_group':
          defaults[name] = [] as FormValues[typeof name];
          break;
        case 'radio':
          defaults[name] = '' as FormValues[typeof name];
          break;
        default:
          defaults[name] = '' as FormValues[typeof name];
          break;
      }

      return defaults;
    }, {}),
  });

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="flex flex-wrap gap-4"
        data-directus={setAttr({
          collection: 'forms',
          item: id,
          fields: 'fields',
          mode: 'popover',
        })}
      >
        {sortedFields.map((field) => (
            <Field key={field.id} field={field} form={form} />
        ))}
        <div className="w-full">
          <div
            data-directus={setAttr({
              collection: 'forms',
              item: id,
              fields: 'submit_label',
              mode: 'popover',
            })}
          >
            <Button type="submit" label={submitLabel} icon="arrow" iconPosition="right" id={`submit-${id || 'form'}`} />
          </div>
        </div>
      </form>
    </Form>
  );
};

export default DynamicForm;
