// cms/nuxt/app/components/PageBuilder.vue
<script setup lang="ts">
interface PageBuilderProps {
	sections: PageBlock[];
}

const props = defineProps<PageBuilderProps>();

const validBlocks = computed(() =>
	props.sections.filter(
		(block): block is PageBlock & { collection: string; item: object } =>
			typeof block.collection === 'string' && !!block.item && typeof block.item === 'object',
	),
);
</script>

<template>
	<div v-for="block in validBlocks" :key="block.id" :data-background="block.background" class="py-16">
		<Container>
			<BaseBlock :block="block" />
		</Container>
	</div>
</template>

// cms/astro/src/components/layout/PageBuilder.tsx
import type { PageBlock } from '@/types/directus-schema';
import BaseBlock from '@/components/blocks/BaseBlock';
import Container from '@/components/ui/Container';

interface PageBuilderProps {
  sections: PageBlock[];
}

const PageBuilder = ({ sections }: PageBuilderProps) => {
  const validBlocks = sections.filter(
    (block): block is PageBlock & { collection: string; item: object } =>
      typeof block.collection === 'string' && !!block.item && typeof block.item === 'object',
  );

  return (
    <div>
      {validBlocks.map((block) => (
        <div key={block.id} data-background={block.background} className="py-16">
          <Container>
            <BaseBlock
              block={{
                collection: block.collection,
                item: block.item,
                id: block.id,
              }}
            />
          </Container>
        </div>
      ))}
    </div>
  );
};

export default PageBuilder;
