// simple-cms/sveltekit/src/lib/components/ui/Container.svelte
<!-- Made by Alex -->
<!-- Not ShadCN -->

<script lang="ts">
	import { cn } from '$lib/utils';
	import type { Snippet } from 'svelte';

	type SemanticElement =
		| 'div'
		| 'section'
		| 'main'
		| 'article'
		| 'aside'
		| 'nav'
		| 'header'
		| 'footer'
		| 'form';

	interface ContainerProps {
		class?: string;
		as?: SemanticElement;
		children: Snippet;
		role?: string;
	}

	const { class: className, as: Component = 'div', children }: ContainerProps = $props();
</script>

<svelte:element this={Component} class={cn('mx-auto max-w-7xl px-4 sm:px-6 lg:px-16', className)}
	>{@render children()}</svelte:element
>

// simple-cms/astro/src/components/ui/Container.tsx
import type { PropsWithChildren } from 'react';
import { cn } from '@/lib/utils';

type SemanticElement = 'div' | 'section' | 'main' | 'article' | 'aside' | 'nav' | 'header' | 'footer' | 'form';
interface ContainerProps extends PropsWithChildren {
  className?: string;
  as?: SemanticElement;
  role?: string;
}

export default function Container({ children = null, className = '', as: Component = 'div', role }: ContainerProps) {
  if (!children) return null;
  return (
    <Component className={cn('max-w-7xl mx-auto px-4 sm:px-6 lg:px-16', className)} role={role}>
      {children}
    </Component>
  );
}
