// cms/sveltekit/src/lib/components/ui/Text.svelte
<script lang="ts">
	import { cn } from '$lib/utils';

	interface TextProps {
		content: string;
		class?: string;
		'data-directus'?: string | undefined;
	}

	let { content, 'data-directus': dataDirectus, ...props }: TextProps = $props();
</script>

<div class={cn('prose dark:prose-invert', props.class)} data-directus={dataDirectus}>
	{@html content}
</div>

// simple-cms/astro/src/components/ui/Text.tsx
import React from 'react';
import { cn } from '@/lib/utils';

export interface TextProps {
  content: string;
  className?: string;
  'data-directus'?: string;
}

const Text = ({ content, className, 'data-directus': dataDirectus }: TextProps) => {
  return (
    <div
      className={cn('prose dark:prose-invert', className)}
      dangerouslySetInnerHTML={{ __html: content }}
      data-directus={dataDirectus}
    />
  );
};

export default Text;
